version: '3'

services:
  web:
    build: ./app
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py 
      - FLASK_ENV=development 
    volumes:
      - .:/app
    
   
